import type { Metadata } from "next";
import "./globals.css";
// import "./embla-carousel.css";
import "./rtl.css";
import FooterNav from "../components/footer/footerNav";
import ReduxProvider from "../components/ReduxProvider";
import CartInitializer from "../components/cart/CartInitializer";
import WishlistInitializer from "../components/wishlist/WishlistInitializer";
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getLocale } from 'next-intl/server';
import NavProgress from "../components/navProgress";
import LayoutWithMenuData from "../components/LayoutWithMenuData";
import ScriptLoader from "../components/ScriptLoader";
import ColorProvider from "../components/ColorProvider";
import BackToTopButton from "../components/BackToTopButton";
import CompareBar from "../components/footer/compareBar";
import CompareInitializer from "../components/compare/CompareInitializer";
import { ThemeProvider } from "../components/ThemeProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  const isRTL = locale === 'ar';
  
  return (
    <html dir={isRTL ? 'rtl' : 'ltr'} lang={locale} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const savedMode = localStorage.getItem('darkMode');
                  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  const shouldBeDark = savedMode === 'true' ? true : savedMode === 'false' ? false : prefersDark;
                  if (shouldBeDark) {
                    document.documentElement.classList.add('dark');
                    document.documentElement.classList.remove('light');
                  } else {
                    document.documentElement.classList.add('light');
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {
                  document.documentElement.classList.add('light');
                  document.documentElement.classList.remove('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`bg-gray-50 text-base font-ltr rtl:font-rtl dark:text-white dark:bg-gray-900 min-h-screen flex flex-col ${isRTL ? 'font-rtl' : 'font-inter'}  ${isRTL ? 'rtl' : 'ltr'}`}
      >
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            <ThemeProvider>
              <div className="flex flex-col min-h-screen" suppressHydrationWarning>
                <NavProgress />
                <CartInitializer />
                <WishlistInitializer />
                <CompareInitializer />
                {/* <HeaderStyle2 /> */}
                <LayoutWithMenuData>
                <ColorProvider>
                  <main className="flex-1 pb-16 lg:pb-0">
                    {children}
                  </main>
                  </ColorProvider>
                </LayoutWithMenuData>
                <BackToTopButton />
              </div>
              <CompareBar />
              <FooterNav />
            </ThemeProvider>
          </ReduxProvider>
          <Toaster position="top-center" /> 
        </NextIntlClientProvider>
        <ScriptLoader />
      </body>
    </html>
  );
}
