import type { Metadata } from "next";
import "./globals.css";
import { getMessages, getLocale } from 'next-intl/server';
import { unstable_cache } from 'next/cache';
import Header from "@/components/header";
import FooterStyle1 from "@/components/footer/styles/footerStyle1";
import ThemeProvider from "../components/themeProvider";
import getRequest from "../../helpers/get";
import { generatePaletteFromHex } from "@/utils/colorUtils";
import { NextIntlClientProvider } from "next-intl";
import MobileMenuFooter from "@/components/mobileMenuFooter/mobileMenuFooter";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function generateColorCSS(colors: Record<string, unknown> | null | undefined): string {
  const c = colors as Record<string, unknown> | undefined;
  const colorsObj = c?.colors as Record<string, unknown> | undefined;
  
  // Colors that will use generatePaletteFromHex
  const primaryColor = (c?.primary_color || c?.primary || colorsObj?.primary) as string | undefined;
  const secondaryColor = (c?.secondary || colorsObj?.secondary) as string | undefined;
  const accentColor = (c?.location_color || c?.accent || colorsObj?.accent) as string | undefined;
  
  // Colors to use as-is (no palette generation)
  const grayColor = (c?.gray || colorsObj?.gray) as string | Record<string, string> | undefined;
  const gradientOne = (c?.gradient_one || colorsObj?.gradient_one) as string | undefined;
  const gradientTwo = (c?.gradient_two || colorsObj?.gradient_two) as string | undefined;
  
  // Other colors (optional)
  const blackColor = (c?.black_color || colorsObj?.black) as string | undefined;
  const titleColor = (c?.title_color || colorsObj?.title) as string | undefined;
  const dividerColor = (c?.divider_color || colorsObj?.divider) as string | undefined;
  const borderColor = (c?.border_color || colorsObj?.border) as string | undefined;
  const redColor = (c?.red_color || colorsObj?.red) as string | undefined;

  let css = ':root {';
  
  // Generate palette for primary color
  if (primaryColor) {
    try {
      const palette = generatePaletteFromHex(primaryColor);
      css += `--apicolor-primary_50: ${palette[50]};`;
      css += `--apicolor-primary_100: ${palette[100]};`;
      css += `--apicolor-primary_200: ${palette[200]};`;
      css += `--apicolor-primary_300: ${palette[300]};`;
      css += `--apicolor-primary_400: ${palette[400]};`;
      css += `--apicolor-primary_500: ${palette[500]};`;
      css += `--apicolor-primary_600: ${palette[600]};`;
      css += `--apicolor-primary_700: ${palette[700]};`;
      css += `--apicolor-primary_800: ${palette[800]};`;
      css += `--apicolor-primary_900: ${palette[900]};`;
    } catch (error) {
      console.error('Error generating primary palette:', error);
      css += `--apicolor-primary_500: ${primaryColor};`;
    }
  }
  
  // Generate palette for secondary color
  if (secondaryColor) {
    try {
      const palette = generatePaletteFromHex(secondaryColor);
      css += `--apicolor-secondary_50: ${palette[50]};`;
      css += `--apicolor-secondary_100: ${palette[100]};`;
      css += `--apicolor-secondary_200: ${palette[200]};`;
      css += `--apicolor-secondary_300: ${palette[300]};`;
      css += `--apicolor-secondary_400: ${palette[400]};`;
      css += `--apicolor-secondary_500: ${palette[500]};`;
      css += `--apicolor-secondary_600: ${palette[600]};`;
      css += `--apicolor-secondary_700: ${palette[700]};`;
      css += `--apicolor-secondary_800: ${palette[800]};`;
      css += `--apicolor-secondary_900: ${palette[900]};`;
    } catch (error) {
      console.error('Error generating secondary palette:', error);
      css += `--apicolor-secondary_500: ${secondaryColor};`;
    }
  }
  
  // Generate palette for accent color
  if (accentColor) {
    try {
      const palette = generatePaletteFromHex(accentColor);
      css += `--apicolor-accent_50: ${palette[50]};`;
      css += `--apicolor-accent_100: ${palette[100]};`;
      css += `--apicolor-accent_200: ${palette[200]};`;
      css += `--apicolor-accent_300: ${palette[300]};`;
      css += `--apicolor-accent_400: ${palette[400]};`;
      css += `--apicolor-accent_500: ${palette[500]};`;
      css += `--apicolor-accent_600: ${palette[600]};`;
      css += `--apicolor-accent_700: ${palette[700]};`;
      css += `--apicolor-accent_800: ${palette[800]};`;
      css += `--apicolor-accent_900: ${palette[900]};`;
    } catch (error) {
      console.error('Error generating accent palette:', error);
      css += `--apicolor-accent_500: ${accentColor};`;
    }
  }
  
  // Use gray as-is (can be a string or object with shades)
  if (grayColor) {
    if (typeof grayColor === 'string') {
      // If it's a single color, use it for all shades
      css += `--apicolor-gray_50: ${grayColor};`;
      css += `--apicolor-gray_100: ${grayColor};`;
      css += `--apicolor-gray_200: ${grayColor};`;
      css += `--apicolor-gray_300: ${grayColor};`;
      css += `--apicolor-gray_400: ${grayColor};`;
      css += `--apicolor-gray_500: ${grayColor};`;
      css += `--apicolor-gray_600: ${grayColor};`;
      css += `--apicolor-gray_700: ${grayColor};`;
      css += `--apicolor-gray_800: ${grayColor};`;
      css += `--apicolor-gray_900: ${grayColor};`;
    } else if (typeof grayColor === 'object') {
      // If it's an object with shades, use them directly
      const gray = grayColor as Record<string, string>;
      if (gray[50]) css += `--apicolor-gray_50: ${gray[50]};`;
      if (gray[100]) css += `--apicolor-gray_100: ${gray[100]};`;
      if (gray[200]) css += `--apicolor-gray_200: ${gray[200]};`;
      if (gray[300]) css += `--apicolor-gray_300: ${gray[300]};`;
      if (gray[400]) css += `--apicolor-gray_400: ${gray[400]};`;
      if (gray[500]) css += `--apicolor-gray_500: ${gray[500]};`;
      if (gray[600]) css += `--apicolor-gray_600: ${gray[600]};`;
      if (gray[700]) css += `--apicolor-gray_700: ${gray[700]};`;
      if (gray[800]) css += `--apicolor-gray_800: ${gray[800]};`;
      if (gray[900]) css += `--apicolor-gray_900: ${gray[900]};`;
    }
  }
  
  // Use gradient_one and gradient_two as-is
  if (gradientOne) css += `--apicolor-gradient_one: ${gradientOne};`;
  if (gradientTwo) css += `--apicolor-gradient_two: ${gradientTwo};`;
  
  // Set additional colors if available (these don't need palettes)
  if (blackColor) css += `--apicolor-black: ${blackColor};`;
  if (titleColor) css += `--apicolor-title: ${titleColor};`;
  if (dividerColor) css += `--apicolor-divider: ${dividerColor};`;
  if (borderColor) css += `--apicolor-border: ${borderColor};`;
  if (redColor) css += `--apicolor-red: ${redColor};`;
  
  css += '}';
  return css;
}

export default async function RootLayout({ 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  const isRTL = locale === 'ar';
  
  // Create cached functions for settings and menu data (3 hours = 10800 seconds)
  const getCachedSettings = unstable_cache(
    async (locale: string) => {
      try {
        const response = await getRequest('/settings', {}, null, locale);
        return response?.data?.settings || response?.data || response;
      } catch (error) {
        console.error('Failed to fetch theme colors on server:', error);
        return null;
      }
    },
    ['settings'], // cache key prefix
    {
      revalidate: 10800, // 3 hours in seconds
      tags: ['settings']
    }
  );

  const getCachedMenuData = unstable_cache(
    async (locale: string) => {
      try {
        return await getRequest('/core/menus', {}, null, locale);
      } catch (error) {
        console.error('❌ Failed to fetch menus server-side:', error);
        return null;
      }
    },
    ['menu-data'], // cache key prefix
    {
      revalidate: 10800, // 3 hours in seconds
      tags: ['menu-data']
    }
  );

  // Fetch colors server-side to prevent flash (cached for 3 hours)
  let colorCSS = '';
  let menuData = null;
  
  const settingsData = await getCachedSettings(locale);
  if (settingsData) {
    colorCSS = generateColorCSS(settingsData);
  }
  
  menuData = await getCachedMenuData(locale);
  
  return (
    <html dir={isRTL ? 'rtl' : 'ltr'} lang={locale} suppressHydrationWarning>
      <head>
        {colorCSS && (
          <style dangerouslySetInnerHTML={{ __html: colorCSS }} />
        )}
      </head>

      <body
        className={`bg-gray-50 text-base font-ltr rtl:font-rtl dark:text-white dark:bg-gray-900 min-h-screen flex flex-col ${isRTL ? 'font-rtl' : 'font-inter'}  ${isRTL ? 'rtl' : 'ltr'}`}
      >
      <NextIntlClientProvider messages={messages}>
          
        <ThemeProvider>
          <Header menuData={menuData} />
          <main className="flex-1 pb-16 lg:pb-0 dark:bg-gray-900 dark:text-white">
            {children}
          </main>
          <FooterStyle1 menuData={menuData} />
          <MobileMenuFooter />
          <Toaster />
        </ThemeProvider>

        </NextIntlClientProvider>
      </body>
    </html>
  );
}
