import type { Metadata } from "next";
import "./globals.css";
// import "./embla-carousel.css";
import "./rtl.css";
import FooterNav from "../components/footer/footerNav";
import ReduxProvider from "../components/ReduxProvider";
import CartInitializer from "../components/cart/CartInitializer";
import WishlistInitializer from "../components/wishlist/WishlistInitializer";
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getLocale } from 'next-intl/server';
import NavProgress from "../components/navProgress";
import LayoutWithMenuData from "../components/LayoutWithMenuData";
// import ScriptLoader from "../components/ScriptLoader";
// import BackToTopButton from "../components/BackToTopButton";
import CompareBar from "../components/footer/compareBar";
import CompareInitializer from "../components/compare/CompareInitializer";
import { ThemeProvider } from "../components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  const isRTL = locale === 'ar';
  
  return (
    <html dir={isRTL ? 'rtl' : 'ltr'} lang={locale} suppressHydrationWarning>
      <head>
      <style dangerouslySetInnerHTML={{
        __html: `
          html:not([data-colors-loaded]) body {
            visibility: hidden;
            opacity: 0;
          }
          html[data-colors-loaded] body {
            visibility: visible;
            opacity: 1;
            transition: opacity 0.2s ease-in;
          }
        `
      }} />
      <script
    dangerouslySetInnerHTML={{
      __html: `
        (function() {
          try {
            const CACHE_KEY = 'color_settings_cache';
            const CACHE_DURATION = 3 * 60 * 60 * 1000; // 3 hours
            const API_BASE_URL = '${process.env.NEXT_PUBLIC_API_BASE_URL || ''}';
            
            // Convert hex to HSL (matching tailwindPlugins/colors.js)
            function hexToHSL(H) {
              let r = 0, g = 0, b = 0;
              if (H.length === 4) {
                r = "0x" + H[1] + H[1];
                g = "0x" + H[2] + H[2];
                b = "0x" + H[3] + H[3];
              } else if (H.length === 7) {
                r = "0x" + H[1] + H[2];
                g = "0x" + H[3] + H[4];
                b = "0x" + H[5] + H[6];
              }
              r /= 255;
              g /= 255;
              b /= 255;
              const cmin = Math.min(r, g, b);
              const cmax = Math.max(r, g, b);
              const delta = cmax - cmin;
              let h = 0, s = 0, l = (cmax + cmin) / 2;
              if (delta !== 0) {
                h = cmax === r ? ((g - b) / delta) % 6 :
                    cmax === g ? (b - r) / delta + 2 :
                        (r - g) / delta + 4;
                h = Math.round(h * 60);
                if (h < 0) h += 360;
                s = delta / (1 - Math.abs(2 * l - 1));
              }
              s = +(s * 100).toFixed(1);
              l = +(l * 100).toFixed(1);
              return [h, s, l];
            }
            
            function hsl(h, s, l) {
              return 'hsl(' + h + ', ' + s + '%, ' + l + '%)';
            }
            
            function generatePalette(h, s, l) {
              return {
                50: hsl(h, s, Math.min(l + 45, 95)),
                100: hsl(h, s, Math.min(l + 35, 90)),
                200: hsl(h, s, Math.min(l + 25, 80)),
                300: hsl(h, s, Math.min(l + 15, 70)),
                400: hsl(h, s, Math.min(l + 7, 60)),
                500: hsl(h, s, l),
                600: hsl(h, s, Math.max(l - 7, 5)),
                700: hsl(h, s, Math.max(l - 15, 5)),
                800: hsl(h, s, Math.max(l - 25, 3)),
                900: hsl(h, s, Math.max(l - 35, 2))
              };
            }
            
            function generatePaletteFromHex(hex) {
              const hsl = hexToHSL(hex);
              return generatePalette(hsl[0], hsl[1], hsl[2]);
            }
            
            function applyColors(colors) {
              const root = document.documentElement;
              Object.entries(colors).forEach(function([key, value]) {
                const baseName = key.replace('_color', '');
                const cssVar = '--apicolor-' + baseName;
                root.style.setProperty(cssVar, value);
                
                if (key.endsWith('_color') && typeof value === 'string' && value.startsWith('#')) {
                  const shades = generatePaletteFromHex(value);
                  Object.entries(shades).forEach(function([step, shade]) {
                    root.style.setProperty('--apicolor-' + baseName + '_' + step, shade);
                  });
                }
              });
              // Mark colors as loaded
              document.documentElement.setAttribute('data-colors-loaded', 'true');
            }
            
            // Check for existing cache first
            const cached = localStorage.getItem(CACHE_KEY);
            let colorsToApply = null;
            
            if (cached) {
              try {
                const cachedData = JSON.parse(cached);
                const now = Date.now();
                const isExpired = now - cachedData.timestamp > CACHE_DURATION;
                
                if (!isExpired && cachedData.colors) {
                  colorsToApply = cachedData.colors;
                }
              } catch (e) {
                // Invalid cache data
              }
            }
            
            // Apply cached colors immediately if available
            if (colorsToApply) {
              applyColors(colorsToApply);
            } else if (API_BASE_URL) {
              // Fetch from API and wait for response before showing content
              fetch(API_BASE_URL + '/settings')
                .then(function(response) {
                  return response.json();
                })
                .then(function(data) {
                  const colors = data?.data?.settings;
                  if (colors) {
                    // Cache the colors
                    try {
                      const cachedData = {
                        colors: colors,
                        timestamp: Date.now()
                      };
                      localStorage.setItem(CACHE_KEY, JSON.stringify(cachedData));
                    } catch (e) {
                      // localStorage might be unavailable
                    }
                    
                    // Apply the colors
                    applyColors(colors);
                  } else {
                    // No colors from API, show content anyway
                    document.documentElement.setAttribute('data-colors-loaded', 'true');
                  }
                })
                .catch(function(err) {
                  console.error('Failed to fetch colors:', err);
                  // On error, show content anyway
                  document.documentElement.setAttribute('data-colors-loaded', 'true');
                });
            } else {
              // No API URL, show content immediately
              document.documentElement.setAttribute('data-colors-loaded', 'true');
            }
          } catch (e) {
            // On any error, show content anyway
            document.documentElement.setAttribute('data-colors-loaded', 'true');
          }
        })();
      `
    }}
  />
      </head>
      <body
        className={`bg-gray-50 text-base font-ltr rtl:font-rtl dark:text-white dark:bg-gray-900 min-h-screen flex flex-col ${isRTL ? 'font-rtl' : 'font-inter'}  ${isRTL ? 'rtl' : 'ltr'}`}
      >
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
          <ThemeProvider>
          <NavProgress />
          <CartInitializer />
          <WishlistInitializer />
          <CompareInitializer />

      
                <LayoutWithMenuData>
                  <main className="flex-1 pb-16 lg:pb-0">
                    {children}
                  </main>
                </LayoutWithMenuData>
          <Toaster position="top-center" /> 
          <CompareBar />
          <FooterNav />
          </ThemeProvider>
          </ReduxProvider>
          </NextIntlClientProvider>

      </body>
    </html>
  );
}
